collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.8793401706498116
  brandStrength: 0.6021277
  lightness: 0.05273481993936002
  brandColors:
    - '#FFFFFF'
    - '#C22226'
    - '#000000'
    - '#494949'
    - '#D45F63'
  rhythmicContrast: 0.3974324560258538
typography_spectrum: 0.2638298
layout_spectrum: 0.2297872
name: wunntee
